package id.ac.itats.skripsi.ainul;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import id.ac.itats.skripsi.ainul.HasilFloydWarshallbDao;
import id.ac.itats.skripsi.ainul.HasilFloydWarshallDao;
import id.ac.itats.skripsi.ainul.NodeMasterDao;
import id.ac.itats.skripsi.ainul.SatuArah1Dao;
import id.ac.itats.skripsi.ainul.SatuArahDao;
import id.ac.itats.skripsi.ainul.Matriks_jarak_predecessor_inisialisasi_masterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        HasilFloydWarshallbDao.createTable(db, ifNotExists);
        HasilFloydWarshallDao.createTable(db, ifNotExists);
        NodeMasterDao.createTable(db, ifNotExists);
        SatuArah1Dao.createTable(db, ifNotExists);
        SatuArahDao.createTable(db, ifNotExists);
        Matriks_jarak_predecessor_inisialisasi_masterDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        HasilFloydWarshallbDao.dropTable(db, ifExists);
        HasilFloydWarshallDao.dropTable(db, ifExists);
        NodeMasterDao.dropTable(db, ifExists);
        SatuArah1Dao.dropTable(db, ifExists);
        SatuArahDao.dropTable(db, ifExists);
        Matriks_jarak_predecessor_inisialisasi_masterDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(HasilFloydWarshallbDao.class);
        registerDaoClass(HasilFloydWarshallDao.class);
        registerDaoClass(NodeMasterDao.class);
        registerDaoClass(SatuArah1Dao.class);
        registerDaoClass(SatuArahDao.class);
        registerDaoClass(Matriks_jarak_predecessor_inisialisasi_masterDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
