package id.ac.itats.skripsi.ainul;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import id.ac.itats.skripsi.ainul.HasilFloydWarshallb;
import id.ac.itats.skripsi.ainul.HasilFloydWarshall;
import id.ac.itats.skripsi.ainul.NodeMaster;
import id.ac.itats.skripsi.ainul.SatuArah1;
import id.ac.itats.skripsi.ainul.SatuArah;
import id.ac.itats.skripsi.ainul.Matriks_jarak_predecessor_inisialisasi_master;

import id.ac.itats.skripsi.ainul.HasilFloydWarshallbDao;
import id.ac.itats.skripsi.ainul.HasilFloydWarshallDao;
import id.ac.itats.skripsi.ainul.NodeMasterDao;
import id.ac.itats.skripsi.ainul.SatuArah1Dao;
import id.ac.itats.skripsi.ainul.SatuArahDao;
import id.ac.itats.skripsi.ainul.Matriks_jarak_predecessor_inisialisasi_masterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hasilFloydWarshallbDaoConfig;
    private final DaoConfig hasilFloydWarshallDaoConfig;
    private final DaoConfig nodeMasterDaoConfig;
    private final DaoConfig satuArah1DaoConfig;
    private final DaoConfig satuArahDaoConfig;
    private final DaoConfig matriks_jarak_predecessor_inisialisasi_masterDaoConfig;

    private final HasilFloydWarshallbDao hasilFloydWarshallbDao;
    private final HasilFloydWarshallDao hasilFloydWarshallDao;
    private final NodeMasterDao nodeMasterDao;
    private final SatuArah1Dao satuArah1Dao;
    private final SatuArahDao satuArahDao;
    private final Matriks_jarak_predecessor_inisialisasi_masterDao matriks_jarak_predecessor_inisialisasi_masterDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hasilFloydWarshallbDaoConfig = daoConfigMap.get(HasilFloydWarshallbDao.class).clone();
        hasilFloydWarshallbDaoConfig.initIdentityScope(type);

        hasilFloydWarshallDaoConfig = daoConfigMap.get(HasilFloydWarshallDao.class).clone();
        hasilFloydWarshallDaoConfig.initIdentityScope(type);

        nodeMasterDaoConfig = daoConfigMap.get(NodeMasterDao.class).clone();
        nodeMasterDaoConfig.initIdentityScope(type);

        satuArah1DaoConfig = daoConfigMap.get(SatuArah1Dao.class).clone();
        satuArah1DaoConfig.initIdentityScope(type);

        satuArahDaoConfig = daoConfigMap.get(SatuArahDao.class).clone();
        satuArahDaoConfig.initIdentityScope(type);

        matriks_jarak_predecessor_inisialisasi_masterDaoConfig = daoConfigMap.get(Matriks_jarak_predecessor_inisialisasi_masterDao.class).clone();
        matriks_jarak_predecessor_inisialisasi_masterDaoConfig.initIdentityScope(type);

        hasilFloydWarshallbDao = new HasilFloydWarshallbDao(hasilFloydWarshallbDaoConfig, this);
        hasilFloydWarshallDao = new HasilFloydWarshallDao(hasilFloydWarshallDaoConfig, this);
        nodeMasterDao = new NodeMasterDao(nodeMasterDaoConfig, this);
        satuArah1Dao = new SatuArah1Dao(satuArah1DaoConfig, this);
        satuArahDao = new SatuArahDao(satuArahDaoConfig, this);
        matriks_jarak_predecessor_inisialisasi_masterDao = new Matriks_jarak_predecessor_inisialisasi_masterDao(matriks_jarak_predecessor_inisialisasi_masterDaoConfig, this);

        registerDao(HasilFloydWarshallb.class, hasilFloydWarshallbDao);
        registerDao(HasilFloydWarshall.class, hasilFloydWarshallDao);
        registerDao(NodeMaster.class, nodeMasterDao);
        registerDao(SatuArah1.class, satuArah1Dao);
        registerDao(SatuArah.class, satuArahDao);
        registerDao(Matriks_jarak_predecessor_inisialisasi_master.class, matriks_jarak_predecessor_inisialisasi_masterDao);
    }
    
    public void clear() {
        hasilFloydWarshallbDaoConfig.getIdentityScope().clear();
        hasilFloydWarshallDaoConfig.getIdentityScope().clear();
        nodeMasterDaoConfig.getIdentityScope().clear();
        satuArah1DaoConfig.getIdentityScope().clear();
        satuArahDaoConfig.getIdentityScope().clear();
        matriks_jarak_predecessor_inisialisasi_masterDaoConfig.getIdentityScope().clear();
    }

    public HasilFloydWarshallbDao getHasilFloydWarshallbDao() {
        return hasilFloydWarshallbDao;
    }

    public HasilFloydWarshallDao getHasilFloydWarshallDao() {
        return hasilFloydWarshallDao;
    }

    public NodeMasterDao getNodeMasterDao() {
        return nodeMasterDao;
    }

    public SatuArah1Dao getSatuArah1Dao() {
        return satuArah1Dao;
    }

    public SatuArahDao getSatuArahDao() {
        return satuArahDao;
    }

    public Matriks_jarak_predecessor_inisialisasi_masterDao getMatriks_jarak_predecessor_inisialisasi_masterDao() {
        return matriks_jarak_predecessor_inisialisasi_masterDao;
    }

}
