package id.ac.itats.skripsi.ainul;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Hasil_Floyd_Warshallb.
 */
public class HasilFloydWarshallb {

    private Long idMatriksjarakInisialisasi;
    private String idNodeAsal;
    private String idNodeTujuan;
    private String jarak;
    private String path;
    private String wayId;

    public HasilFloydWarshallb() {
    }

    public HasilFloydWarshallb(Long idMatriksjarakInisialisasi) {
        this.idMatriksjarakInisialisasi = idMatriksjarakInisialisasi;
    }

    public HasilFloydWarshallb(Long idMatriksjarakInisialisasi, String idNodeAsal, String idNodeTujuan, String jarak, String path, String wayId) {
        this.idMatriksjarakInisialisasi = idMatriksjarakInisialisasi;
        this.idNodeAsal = idNodeAsal;
        this.idNodeTujuan = idNodeTujuan;
        this.jarak = jarak;
        this.path = path;
        this.wayId = wayId;
    }

    public Long getIdMatriksjarakInisialisasi() {
        return idMatriksjarakInisialisasi;
    }

    public void setIdMatriksjarakInisialisasi(Long idMatriksjarakInisialisasi) {
        this.idMatriksjarakInisialisasi = idMatriksjarakInisialisasi;
    }

    public String getIdNodeAsal() {
        return idNodeAsal;
    }

    public void setIdNodeAsal(String idNodeAsal) {
        this.idNodeAsal = idNodeAsal;
    }

    public String getIdNodeTujuan() {
        return idNodeTujuan;
    }

    public void setIdNodeTujuan(String idNodeTujuan) {
        this.idNodeTujuan = idNodeTujuan;
    }

    public String getJarak() {
        return jarak;
    }

    public void setJarak(String jarak) {
        this.jarak = jarak;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getWayId() {
        return wayId;
    }

    public void setWayId(String wayId) {
        this.wayId = wayId;
    }

}
