package id.ac.itats.skripsi.ainul;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Node_Master.
 */
public class NodeMaster {

    private Long idNode;
    private String idNodePeta;
    private String latitude;
    private String longitude;

    public NodeMaster() {
    }

    public NodeMaster(Long idNode) {
        this.idNode = idNode;
    }

    public NodeMaster(Long idNode, String idNodePeta, String latitude, String longitude) {
        this.idNode = idNode;
        this.idNodePeta = idNodePeta;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getIdNode() {
        return idNode;
    }

    public void setIdNode(Long idNode) {
        this.idNode = idNode;
    }

    public String getIdNodePeta() {
        return idNodePeta;
    }

    public void setIdNodePeta(String idNodePeta) {
        this.idNodePeta = idNodePeta;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

}
