package id.ac.itats.skripsi.ainul;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Satu_Arah.
 */
public class SatuArah {

    private Long idSatuArah;
    private String wayId;
    private String satuArah;
    private String namaJalan;

    public SatuArah() {
    }

    public SatuArah(Long idSatuArah) {
        this.idSatuArah = idSatuArah;
    }

    public SatuArah(Long idSatuArah, String wayId, String satuArah, String namaJalan) {
        this.idSatuArah = idSatuArah;
        this.wayId = wayId;
        this.satuArah = satuArah;
        this.namaJalan = namaJalan;
    }

    public Long getIdSatuArah() {
        return idSatuArah;
    }

    public void setIdSatuArah(Long idSatuArah) {
        this.idSatuArah = idSatuArah;
    }

    public String getWayId() {
        return wayId;
    }

    public void setWayId(String wayId) {
        this.wayId = wayId;
    }

    public String getSatuArah() {
        return satuArah;
    }

    public void setSatuArah(String satuArah) {
        this.satuArah = satuArah;
    }

    public String getNamaJalan() {
        return namaJalan;
    }

    public void setNamaJalan(String namaJalan) {
        this.namaJalan = namaJalan;
    }

}
